version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - db_data:/app/data  # Том для хранения базы данных
    environment:
      - FLASK_ENV=development
      - DB_PATH=/app/data/parad.db
    restart: unless-stopped

volumes:
  db_data: